version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: sc-nginx
    restart: always
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./dist:/u01/vue-vben-admin
    networks:
      - sc-net
    ports:
      - 8080:9090

networks:
  sc-net:
    external:
      name: docker-compose_sc-net
