apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: sc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 -f docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-compose_sc-net: 'true'
        io.kompose.service: nginx
    spec:
      containers:
        - image: lo-harbor.yyjzt.com/sassflow/nginx:latest
          name: sc-nginx
          ports:
            - containerPort: 9090
          resources: {}
          volumeMounts:
            - mountPath: /var/log/nginx
              name: nginx-claim0
            - mountPath: /etc/nginx/conf.d
              name: nginx-claim1
            - mountPath: /usr/share/nginx/html/admin
              name: nginx-claim2
      restartPolicy: Always
      volumes:
        - name: nginx-claim0
          persistentVolumeClaim:
            claimName: nginx-claim0
        - name: nginx-claim1
          persistentVolumeClaim:
            claimName: nginx-claim1
        - name: nginx-claim2
          persistentVolumeClaim:
            claimName: nginx-claim2
status: {}
