apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 -f docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: sc
spec:
  type: NodePort
  ports:
    - name: '9090'
      port: 9090
      targetPort: 9090
      nodePort: 9090
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
